project:
  type: website
  execute-dir: project
  output-dir: docs

website:
  title: "Unrivaled Rankings"
  navbar:
    background: '#442176'

format:
  html:
    respect-user-color-scheme: true
    theme:
      light: [flatly, light.scss]
      dark: [darkly, dark.scss]
    css: styles.css
    toc: true



